steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['-f', 'display-parameters-server', 'clean', 'install', '-DskipTests']
    
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/display-parameters', 'display-parameters-server/' ]
  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instance-groups, managed, rolling-action, restart, instance-group-one-micro, --zone=us-central1-a]

images:
  - 'gcr.io/$PROJECT_ID/display-parameters'
